// Toram Online Fill Stats Simulation Constants and Data
// Based on the original t4stat.js

export const MAX_STEPS = 20;
export const BONUS_STEPS = 10;
export const SLOTS = 8;

export const PENALTY_DATA = [0, 0, 20, 45, 80, 125, 180, 245, 320];

export const DEFAULT_WEAPON_RECIPE_POT = 46;
export const DEFAULT_ARMOR_RECIPE_POT = 44;

export const OPTIONS = [
  {
    name: "STR",
    mat: "Beast",
    pot: 5,
    cost: 25,
    cat: "Enhance Stats",
    type: "u",
    bonus: 1,
  },
  {
    name: "STR %",
    mat: "Beast",
    pot: 10,
    cost: 50,
    cat: "Enhance Stats",
    type: "u",
  },
  {
    name: "INT",
    mat: "Wood",
    pot: 5,
    cost: 25,
    cat: "Enhance Stats",
    type: "u",
    bonus: 1,
  },
  {
    name: "INT %",
    mat: "Wood",
    pot: 10,
    cost: 50,
    cat: "Enhance Stats",
    type: "u",
  },
  {
    name: "VIT",
    mat: "Metal",
    pot: 5,
    cost: 25,
    cat: "Enhance Stats",
    type: "u",
    bonus: 1,
  },
  {
    name: "VIT %",
    mat: "Metal",
    pot: 10,
    cost: 50,
    cat: "Enhance Stats",
    type: "u",
  },
  {
    name: "AGI",
    mat: "Cloth",
    pot: 5,
    cost: 25,
    cat: "Enhance Stats",
    type: "u",
    bonus: 1,
  },
  {
    name: "AGI %",
    mat: "Cloth",
    pot: 10,
    cost: 50,
    cat: "Enhance Stats",
    type: "u",
  },
  {
    name: "DEX",
    mat: "Medicine",
    pot: 5,
    cost: 25,
    cat: "Enhance Stats",
    type: "u",
    bonus: 1,
  },
  {
    name: "DEX %",
    mat: "Medicine",
    pot: 10,
    cost: 50,
    cat: "Enhance Stats",
    type: "u",
  },

  {
    name: "Natural HP Regen",
    mat: "Metal",
    pot: 5,
    cost: 25,
    cat: "Enhance HP/MP",
    type: "a",
    bonus: 1,
  },
  {
    name: "Natural HP Regen %",
    mat: "Metal",
    pot: 10,
    cost: 50,
    cat: "Enhance HP/MP",
    type: "a",
  },
  {
    name: "Natural MP Regen",
    mat: "Wood",
    pot: 10,
    cost: 50,
    cat: "Enhance HP/MP",
    type: "a",
    bonus: 1,
    bonusratio: 0.5,
  },
  {
    name: "Natural MP Regen %",
    mat: "Wood",
    pot: 20,
    cost: 100,
    cat: "Enhance HP/MP",
    type: "a",
  },
  {
    name: "MaxHP",
    mat: "Metal",
    pot: 3,
    cost: "16.49",
    cat: "Enhance HP/MP",
    type: "u",
    bonus: 160,
    step: 10,
  },
  {
    name: "MaxHP %",
    mat: "Metal",
    pot: 10,
    cost: 50,
    cat: "Enhance HP/MP",
    type: "u",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "MaxMP",
    mat: "Wood",
    pot: 6,
    cost: "33.49",
    cat: "Enhance HP/MP",
    type: "u",
    max: 15,
    max_only: true,
    step: 10,
    bonus: 10,
    bonusratio: 0.5,
  },

  {
    name: "ATK",
    mat: "Beast",
    pot: 3,
    cost: "16.49",
    cat: "Enhance Attack",
    type: "w",
    bonus: 1,
  },
  {
    name: "ATK %",
    mat: "Beast",
    pot: 10,
    cost: 50,
    cat: "Enhance Attack",
    type: "w",
    bonus: 1,
    bonusratio: 0.5,
  },
  {
    name: "MATK",
    mat: "Wood",
    pot: 3,
    cost: "16.49",
    cat: "Enhance Attack",
    type: "w",
    bonus: 1,
  },
  {
    name: "MATK %",
    mat: "Wood",
    pot: 10,
    cost: 50,
    cat: "Enhance Attack",
    type: "w",
    bonus: 1,
    bonusratio: 0.5,
  },
  {
    name: "Stability %",
    mat: "Medicine",
    pot: 20,
    cost: 100,
    cat: "Enhance Attack",
    type: "u",
  },
  {
    name: "Physical Pierce %",
    mat: "Beast",
    pot: 20,
    cost: 100,
    cat: "Enhance Attack",
    type: "w",
    bonus: 1,
    bonusratio: 2 / 5,
  },
  {
    name: "Magic Pierce %",
    mat: "Wood",
    pot: 20,
    cost: 100,
    cat: "Enhance Attack",
    type: "w",
    bonus: 1,
    bonusratio: 2 / 5,
  },

  {
    name: "DEF",
    mat: "Metal",
    pot: 3,
    cost: "16.49",
    cat: "Enhance Defense",
    type: "a",
    bonus: 10,
  },
  {
    name: "DEF %",
    mat: "Metal",
    pot: 10,
    cost: 50,
    cat: "Enhance Defense",
    type: "a",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "MDEF",
    mat: "Metal",
    pot: 3,
    cost: "16.49",
    cat: "Enhance Defense",
    type: "a",
    bonus: 10,
  },
  {
    name: "MDEF %",
    mat: "Metal",
    pot: 10,
    cost: 50,
    cat: "Enhance Defense",
    type: "a",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "Physical Resistance %",
    mat: "Metal",
    pot: 10,
    cost: 50,
    cat: "Enhance Defense",
    type: "a",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "Magical Resistance %",
    mat: "Wood",
    pot: 10,
    cost: 50,
    cat: "Enhance Defense",
    type: "a",
    bonus: 1,
    bonusratio: 1 / 3,
  },

  {
    name: "Reduce Dmg (Foe Epicenter) %",
    mat: "Metal",
    pot: 6,
    cost: 15,
    cat: "Enhance Defense",
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Player Epicenter) %",
    mat: "Metal",
    pot: 6,
    cost: 15,
    cat: "Enhance Defense",
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Straight Line) %",
    mat: "Wood",
    pot: 6,
    cost: 15,
    cat: "Enhance Defense",
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Charge) %",
    mat: "Wood",
    pot: 6,
    cost: 15,
    cat: "Enhance Defense",
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Meteor) %",
    mat: "Wood",
    pot: 4,
    cost: 15,
    cat: "Enhance Defense",
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Bullet) %",
    mat: "Wood",
    pot: 4,
    cost: 15,
    cat: "Enhance Defense",
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Bowling) %",
    mat: "Wood",
    pot: 4,
    cost: 15,
    cat: "Enhance Defense",
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },
  {
    name: "Reduce Dmg (Floor) %",
    mat: "Wood",
    pot: 4,
    cost: 15,
    cat: "Enhance Defense",
    type: "a",
    nonega: true,
    max: BONUS_STEPS,
  },

  {
    name: "Accuracy",
    mat: "Medicine",
    pot: 10,
    cost: 50,
    cat: "Enhance Accuracy",
    type: "w",
    bonus: 2,
    bonusratio: 2 / 3,
  },
  {
    name: "Accuracy %",
    mat: "Medicine",
    pot: 20,
    cost: 100,
    cat: "Enhance Accuracy",
    type: "w",
    bonus: 1,
    bonusratio: 1 / 5,
  },

  {
    name: "Dodge",
    mat: "Cloth",
    pot: 10,
    cost: 50,
    cat: "Enhance Dodge",
    type: "a",
    bonus: 2,
    bonusratio: 2 / 3,
  },
  {
    name: "Dodge %",
    mat: "Cloth",
    pot: 20,
    cost: 100,
    cat: "Enhance Dodge",
    type: "a",
  },

  {
    name: "ASPD",
    mat: "Cloth",
    pot: 1,
    cost: "1.49",
    cat: "Enhance Speed",
    type: "u",
    bonus: 16,
  },
  {
    name: "ASPD %",
    mat: "Cloth",
    pot: 1,
    cost: 5,
    cat: "Enhance Speed",
    type: "u",
  },
  {
    name: "CSPD",
    mat: "Medicine",
    pot: 1,
    cost: "1.49",
    cat: "Enhance Speed",
    type: "u",
    bonus: 16,
  },
  {
    name: "CSPD %",
    mat: "Medicine",
    pot: 1,
    cost: 5,
    cat: "Enhance Speed",
    type: "u",
  },

  {
    name: "Critical Rate",
    mat: "Mana",
    pot: 1,
    cost: 5,
    cat: "Enhance Critical",
    type: "u",
    bonus: 1,
    max_only: true,
  },
  {
    name: "Critical Rate %",
    mat: "Mana",
    pot: 1,
    cost: 5,
    cat: "Enhance Critical",
    type: "u",
    bonus: 1,
    max_only: true,
  },
  {
    name: "Critical Damage",
    mat: "Mana",
    pot: 3,
    cost: "16.49",
    cat: "Enhance Critical",
    type: "u",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "Critical Damage %",
    mat: "Mana",
    pot: 10,
    cost: 50,
    cat: "Enhance Critical",
    type: "u",
    bonus: 1,
    bonusratio: 1 / 8,
  },

  {
    name: "% stronger against Fire",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Water",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Wind",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Earth",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Light",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "% stronger against Dark",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "w",
    bonus: 1,
    bonusratio: 1 / 3,
  },
  {
    name: "Fire resistance %",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Water resistance %",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Wind resistance %",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Earth resistance %",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Light resistance %",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },
  {
    name: "Dark resistance %",
    mat: "Mana",
    pot: 5,
    cost: 25,
    cat: "Enhance Elements",
    type: "a",
    bonus: 1,
    bonusratio: 2 / 3,
  },

  {
    name: "Ailment Resistance %",
    mat: "Mana",
    pot: 20,
    cost: 100,
    cat: "Special Enhancement",
    type: "u",
  },
  {
    name: "Guard Power %",
    mat: "Mana",
    pot: 20,
    cost: 100,
    cat: "Special Enhancement",
    type: "u",
  },
  {
    name: "Guard Rate %",
    mat: "Mana",
    pot: 20,
    cost: 100,
    cat: "Special Enhancement",
    type: "u",
  },
  {
    name: "Evasion Rate %",
    mat: "Mana",
    pot: 20,
    cost: 100,
    cat: "Special Enhancement",
    type: "u",
  },
  {
    name: "Aggro %",
    mat: "Mana",
    pot: 6,
    cost: "33.49",
    cat: "Special Enhancement",
    type: "u",
    max: 15,
    max_only: true,
    bonus: 1,
    bonusratio: 2 / 5,
  },

  {
    name: "Fire Element",
    mat: "Mana",
    pot: 100,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Water Element",
    mat: "Mana",
    pot: 100,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Wind Element",
    mat: "Mana",
    pot: 100,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Earth Element",
    mat: "Mana",
    pot: 100,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Light Element",
    mat: "Mana",
    pot: 100,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Dark Element",
    mat: "Mana",
    pot: 100,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Fire Element (matching)",
    mat: "Mana",
    pot: 10,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Water Element (matching)",
    mat: "Mana",
    pot: 10,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Wind Element (matching)",
    mat: "Mana",
    pot: 10,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Earth Element (matching)",
    mat: "Mana",
    pot: 10,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Light Element (matching)",
    mat: "Mana",
    pot: 10,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
  {
    name: "Dark Element (matching)",
    mat: "Mana",
    pot: 10,
    cost: 150,
    cat: "Awaken Elements",
    type: "e",
    max: 1,
    nonega: true,
  },
];

export function toram_round(value) {
  if (value > 0) return Math.floor(value);
  return Math.ceil(value);
}

export function deep_clone(obj) {
  let type = typeof obj;
  if (Array.isArray(obj)) type = "array";

  let newObj;
  switch (type) {
    case "string":
      newObj = "" + obj;
      break;
    case "array":
      newObj = obj.slice(0).map((i) => deep_clone(i));
      break;
    case "number":
      newObj = 0 + obj;
      break;
    case "boolean":
      newObj = !!obj;
      break;
    case "function":
      newObj = Object.assign({}, { func: obj }).func;
      break;
    case "object":
      // null is a special case
      if (obj === null) return null;

      newObj = {};
      for (let prop in obj) {
        newObj[prop] = deep_clone(obj[prop]);
      }
  }

  return newObj;
}
